version: '3'
services:
  db:
    container_name: supermercado_2
    image: postgres:14.4
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  pgdata:
