version: '3'
services:
  db:
    container_name: proyecto_1_te
    image: postgres:14.4
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./procedures.sql:/docker-entrypoint-initdb.d/create_procedures.sql
      - ./database.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./seed.sql:/seed.sql
      - ./drop.sql:/drop.sql

volumes:
  pgdata:
